services:
  - type: web
    name: alerting-and-notification-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
    plan: free
    branch: main